// <auto-generated />

#nullable disable

using MH.Capstone.Domain.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace MH.Capstone.Domain.Migrations.Cache
{
    [DbContext(typeof(CacheDbContext))]
    [Migration("20260317121744_AddCacheDbContextAndAnimalApiCache")]
    partial class AddCacheDbContextAndAnimalApiCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MH.Capstone.Domain.DataModels.NinjaAnimalCacheEntity", b =>
                {
                    b.Property<string>("Url")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("QueryParams")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CachedResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Url", "QueryParams");

                    b.ToTable("AnimalApiCache");
                });
#pragma warning restore 612, 618
        }
    }
}
