using FluentAssertions;
using MH.Capstone.Domain.DataAccess;
using MH.Capstone.Domain.DataModels;
using MH.Capstone.Tests.Acceptance.Configuration;
using MH.Capstone.Tests.Acceptance.Drivers;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;
using Reqnroll;
using MH.Capstone.Tests.Acceptance.Helpers;

namespace MH.Capstone.Tests.Acceptance.StepDefinitions
{
    [Binding]
    [Scope(Tag = "photo-quality")]
    public class CSP122StepDefinitions
    {
        private const string AlexEmail = "alex@test.com";

        private readonly IWebDriver _webDriver;
        private readonly WebDriverWait _wait;
        private readonly SightingsDriver _sightingsDriver;
        private readonly string _baseUrl;
        private readonly string _dashboardUrl;

        // Holds the path of an image generated by a When step so [AfterScenario] can clean it up.
        private string? _generatedImagePath;

        // Unique description set by the When step and consumed by Then steps to look up
        // exactly the sighting that was just submitted (avoids cross-scenario aliasing
        // when the seeder isn't reset between scenarios).
        private string? _currentSightingDescription;

        public CSP122StepDefinitions(IWebDriver webDriver, WebDriverWait wait,
            AcceptanceTestSettings settings, SightingsDriver sightingsDriver)
        {
            _webDriver = webDriver;
            _wait = wait;
            _sightingsDriver = sightingsDriver;
            _baseUrl = settings.BaseUrl.TrimEnd('/');
            _dashboardUrl = $"{_baseUrl}/Dashboard";
        }

        // Earlier scenarios in the suite can leave a different user (e.g. a
        // dynamically-registered "TestAlex…" account from CSP-47/CSP-134) signed
        // in, which IsUserLoggedIn matches against "alex" by substring and then
        // skips the real login. Clearing cookies before each photo-quality
        // scenario forces "Given user Alex is logged in" to actually authenticate.
        [BeforeScenario("photo-quality")]
        public void ResetSessionCookies()
        {
            _webDriver.Navigate().GoToUrl(_baseUrl);
            _webDriver.Manage().Cookies.DeleteAllCookies();
        }

        [AfterScenario("photo-quality")]
        public void CleanupGeneratedImage()
        {
            if (_generatedImagePath is not null && File.Exists(_generatedImagePath))
                File.Delete(_generatedImagePath);
        }

        #region Given

        [Given("Alex is on the Sighting Upload page")]
        public void GivenAlexIsOnTheSightingUploadPage()
        {
            _sightingsDriver.NavigateToSightingsUpload();
        }

        #endregion

        #region When

        [When("Alex submits a sighting with a {string} image")]
        [When("Alex submits a sighting with an {string} image")]
        public void WhenAlexSubmitsASightingWithAnImage(string imageQuality)
        {
            _generatedImagePath = TestImageFactory.CreateByQuality(imageQuality);

            // Fill in the other required fields with sensible defaults so the upload form
            // passes server-side validation and reaches the photo-quality analyzer.
            // NOTE: timestamp must use LOCAL time (DateTimeOffset.Now) — the form input is
            // formatted as "yyyy-MM-ddTHH:mm" with no offset, so MVC re-parses it as local
            // time. Using UtcNow here would put the value in the future from the server's
            // perspective and trip the [PastDateTime] validator.
            // Make the description globally unique so the Then-step lookup can match it
            // even when sibling scenarios in the same run have already inserted rows.
            _currentSightingDescription = $"CSP-122 {imageQuality} {Guid.NewGuid():N}";

            _sightingsDriver.SetLatitude(44.847600);
            _sightingsDriver.SetLongitude(-123.234300);
            _sightingsDriver.SetTimestamp(DateTimeOffset.Now.AddDays(-1));
            _sightingsDriver.SetDescription(_currentSightingDescription);

            _sightingsDriver.UploadFileAndSubmit(_generatedImagePath);

            // Successful upload redirects to /Dashboard. Wait for that before asserting anything.
            _wait.Until(d => d.Url.Contains("/Dashboard", StringComparison.InvariantCultureIgnoreCase));
        }

        #endregion

        #region Then

        [Then("Alex should see the warning {string}")]
        public void ThenAlexShouldSeeTheWarning(string warningText)
        {
            var element = _wait.Until(d => d.FindElement(By.Id("photoQualityWarning")));
            element.Text.Should().Contain(warningText);
        }

        [Then("Alex should see the badge {string}")]
        public void ThenAlexShouldSeeTheBadge(string badgeText)
        {
            var element = _wait.Until(d => d.FindElement(By.Id("photoQualityBadge")));
            element.Text.Should().Contain(badgeText);
        }

        [Then("the saved sighting should have QualityTier {string}")]
        public void ThenTheSavedSightingShouldHaveQualityTier(string expectedTier)
        {
            var expected = Enum.Parse<PhotoQualityTier>(expectedTier);
            var sighting = GetMostRecentSightingForAlex();
            sighting.QualityTier.Should().Be(expected);
        }

        [Then("the saved sighting's SharpnessScore should be recorded")]
        public void ThenTheSavedSightingsSharpnessScoreShouldBeRecorded()
        {
            var sighting = GetMostRecentSightingForAlex();
            sighting.SharpnessScore.Should().NotBeNull("CSP-122 service must populate SharpnessScore");
        }

        [Then("the saved sighting's LuminanceAverage should be recorded")]
        public void ThenTheSavedSightingsLuminanceAverageShouldBeRecorded()
        {
            var sighting = GetMostRecentSightingForAlex();
            sighting.LuminanceAverage.Should().NotBeNull("CSP-122 service must populate LuminanceAverage");
        }

        #endregion

        #region Helpers — DB access

        private Sighting GetMostRecentSightingForAlex()
        {
            using var scope = GetServiceScope();
            var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

            var alex = dbContext.Users
                .AsNoTracking()
                .FirstOrDefault(u => u.Email == AlexEmail)
                ?? throw new InvalidOperationException(
                    $"Acceptance seed missing: no AspNetUser with Email '{AlexEmail}'.");

            // Match strictly by the per-scenario unique description so cross-feature
            // scenarios (e.g. CSP-53's valid-upload also under Alex with a different
            // timestamp band) can't alias to the wrong row. Description is server-side
            // unique per scenario (CSP-122 prefix + scenario quality + GUID).
            var sighting = dbContext.Set<Sighting>()
                .AsNoTracking()
                .Where(s => s.UserIdentityId == alex.Id && s.Description == _currentSightingDescription)
                .FirstOrDefault()
                ?? throw new InvalidOperationException(
                    $"No sighting found for {AlexEmail} with description '{_currentSightingDescription}'.");

            return sighting;
        }

        // Reuse the live WebApp's DI container — it already has ApplicationDbContext
        // configured with whichever connection string the host resolved (file or env var),
        // so this works equally well in CI (env vars) and locally (appsettings file).
        private static IServiceScope GetServiceScope()
        {
            var appServices = TestWebAppHost.Services
                ?? throw new InvalidOperationException(
                    "TestWebAppHost has not started; cannot resolve web app services.");
            return appServices.CreateScope();
        }

        #endregion
    }
}
