using FluentAssertions;
using MH.Capstone.Tests.Acceptance.Configuration;
using MH.Capstone.Tests.Acceptance.Drivers;
using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;
using Reqnroll;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

namespace MH.Capstone.Tests.Acceptance.StepDefinitions
{
    [Binding]
    [Scope(Tag = "ai-recognition")]
    public class CSP144StepDefinitions
    {
        private readonly IWebDriver _webDriver;
        private readonly WebDriverWait _wait;
        private readonly SightingsDriver _sightingsDriver;
        private readonly string _baseUrl;

        // Holds the path of an image generated by a When step so [AfterScenario] can clean it up.
        private string? _generatedImagePath;

        public CSP144StepDefinitions(IWebDriver webDriver, WebDriverWait wait,
            AcceptanceTestSettings settings, SightingsDriver sightingsDriver)
        {
            _webDriver = webDriver;
            _wait = wait;
            _sightingsDriver = sightingsDriver;
            _baseUrl = settings.BaseUrl.TrimEnd('/');
        }

        // Earlier scenarios in the suite can leave a different user (e.g. a
        // dynamically-registered "TestAlex…" account) signed in; AuthenticationDriver
        // matches "alex" by substring and skips the real login. Clearing cookies forces
        // the "Given user Alex is logged in" step to actually authenticate.
        [BeforeScenario("ai-recognition")]
        public void ResetSessionCookies()
        {
            _webDriver.Navigate().GoToUrl(_baseUrl);
            _webDriver.Manage().Cookies.DeleteAllCookies();
        }

        [AfterScenario("ai-recognition")]
        public void CleanupGeneratedImage()
        {
            if (_generatedImagePath is not null && File.Exists(_generatedImagePath))
                File.Delete(_generatedImagePath);
        }

        #region Given

        [Given("Alex is on the Sighting Upload page")]
        public void GivenAlexIsOnTheSightingUploadPage()
        {
            _sightingsDriver.NavigateToSightingsUpload();
        }

        #endregion

        #region When

        // Different test photos route through different fetch interceptors so the BDD
        // suite is fully deterministic — the real Gemini API is never called from these
        // tests. The GeminiAIService unit tests cover the real integration path.
        [When("Alex selects a {string} photo and clicks \"Identify with AI\"")]
        public void WhenAlexSelectsAPhotoAndClicksIdentifyWithAI(string photoKind)
        {
            _generatedImagePath = GenerateValidUploadImage();
            InstallSightingAIFetchStub(photoKind);

            // Set the file input first so the "Identify" button has something to send
            _sightingsDriver.SetImageForUpload(_generatedImagePath);

            var identifyBtn = _wait.Until(d =>
            {
                var el = d.FindElement(By.Id("identifyAIBtn"));
                return (el.Displayed && el.Enabled) ? el : null;
            });
            ((IJavaScriptExecutor)_webDriver).ExecuteScript("arguments[0].click();", identifyBtn);
        }

        #endregion

        #region Then

        [Then("Alex should see a species suggestion badge with non-empty text")]
        public void ThenAlexShouldSeeASpeciesSuggestionBadge()
        {
            var badge = _wait.Until(d =>
            {
                var el = d.FindElement(By.Id("aiSuggestionBadge"));
                return el.Displayed ? el : null;
            });
            badge!.Text.Should().NotBeNullOrWhiteSpace(
                "the AI badge should contain the suggested species name");
        }

        [Then("the Description field is populated with non-empty text")]
        public void ThenTheDescriptionFieldIsPopulated()
        {
            var description = _wait.Until(d => d.FindElement(By.Id("Description")));
            description.GetAttribute("value").Should().NotBeNullOrWhiteSpace(
                "the AI suggestion should pre-fill the Description field");
        }

        [Then("Alex should see a \"could not identify\" message")]
        public void ThenAlexShouldSeeACouldNotIdentifyMessage()
        {
            var msg = _wait.Until(d =>
            {
                var el = d.FindElement(By.Id("aiNotIdentifiedMessage"));
                return el.Displayed ? el : null;
            });
            msg!.Text.Should().Contain("identify");
        }

        [Then("the Description field is not auto-filled")]
        public void ThenTheDescriptionFieldIsNotAutoFilled()
        {
            var description = _webDriver.FindElement(By.Id("Description"));
            (description.GetAttribute("value") ?? string.Empty).Should().BeEmpty(
                "non-wildlife photos must not auto-fill the description");
        }

        [Then("Alex should see an AI error message")]
        public void ThenAlexShouldSeeAnAIErrorMessage()
        {
            var err = _wait.Until(d =>
            {
                var el = d.FindElement(By.Id("aiErrorToast"));
                return el.Displayed ? el : null;
            });
            err!.Text.Should().NotBeNullOrWhiteSpace();
        }

        [Then("Alex can still type a description manually and submit the sighting")]
        public void ThenAlexCanStillSubmitManually()
        {
            // Form must remain interactive — fill required fields and submit, expect
            // the post-submit redirect to /Dashboard.
            _sightingsDriver.SetLatitude(44.847600);
            _sightingsDriver.SetLongitude(-123.234300);
            _sightingsDriver.SetTimestamp(DateTimeOffset.Now.AddDays(-1));
            _sightingsDriver.SetDescription("Manually typed because AI was unavailable.");
            _sightingsDriver.SubmitSightingsForm();

            _wait.Until(d => d.Url.Contains("/Dashboard", StringComparison.InvariantCultureIgnoreCase));
        }

        #endregion

        #region Helpers

        // Generates a valid 1024×1024 JPEG so the CSP-122 photo quality gate (long side
        // ≥ 1024 px) does not reject the image when the form is submitted for real.
        private static string GenerateValidUploadImage()
        {
            var path = Path.Combine(Path.GetTempPath(), $"csp144_{Guid.NewGuid():N}.jpg");
            using var image = new Image<Rgb24>(1024, 1024);
            image.SaveAsJpeg(path);
            return path;
        }

        // Replaces window.fetch in the browser so /SightingAI/Identify returns a known
        // response per scenario, without ever touching the real Gemini API.
        private void InstallSightingAIFetchStub(string photoKind)
        {
            string mockBody;
            int status;
            bool ok;

            switch (photoKind)
            {
                case "wildlife":
                    mockBody = @"{""species"":""Bald Eagle"",""description"":""Adult bald eagle on a pine."",""identified"":true}";
                    status = 200; ok = true; break;
                case "non-wildlife":
                    mockBody = @"{""species"":""Unknown"",""description"":""no wildlife visible"",""identified"":false}";
                    status = 200; ok = true; break;
                case "service-down":
                    mockBody = @"{""message"":""Could not reach the AI service.""}";
                    status = 503; ok = false; break;
                default:
                    throw new ArgumentException($"Unsupported photo kind '{photoKind}'", nameof(photoKind));
            }

            var script = $@"
                (function() {{
                    if (window.__csp144FetchStub) return 'already-installed';
                    window.__csp144FetchStub = true;
                    var orig = window.fetch;
                    window.fetch = function(input, init) {{
                        var url = (typeof input === 'string') ? input : (input && input.url) || '';
                        if (url.indexOf('/SightingAI/Identify') !== -1) {{
                            var body = '{mockBody}';
                            return Promise.resolve({{
                                ok: {ok.ToString().ToLower()},
                                status: {status},
                                json: function() {{ return Promise.resolve(JSON.parse(body)); }},
                                text: function() {{ return Promise.resolve(body); }}
                            }});
                        }}
                        return orig.apply(this, arguments);
                    }};
                    return 'installed';
                }})();";

            ((IJavaScriptExecutor)_webDriver).ExecuteScript(script);
        }

        #endregion
    }
}
