using FluentAssertions;
using MH.Capstone.Domain.DataAccess;
using MH.Capstone.Domain.DataModels;
using MH.Capstone.Tests.Acceptance.Configuration;
using MH.Capstone.Tests.Acceptance.Drivers;
using Microsoft.AspNetCore.Identity;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;
using Reqnroll;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using System.Text.Json;

namespace MH.Capstone.Tests.Acceptance.StepDefinitions
{
    [Binding]
    [Scope(Tag = "photo-quality")]
    public class CSP122StepDefinitions
    {
        private const string AlexEmail = "alex@test.com";

        private readonly IWebDriver _webDriver;
        private readonly WebDriverWait _wait;
        private readonly SightingsDriver _sightingsDriver;
        private readonly string _dashboardUrl;

        // Holds the path of an image generated by a When step so [AfterScenario] can clean it up.
        private string? _generatedImagePath;

        // Unique description set by the When step and consumed by Then steps to look up
        // exactly the sighting that was just submitted (avoids cross-scenario aliasing
        // when the seeder isn't reset between scenarios).
        private string? _currentSightingDescription;

        private static readonly Lazy<string?> _connectionString = new(LoadConnectionString);

        public CSP122StepDefinitions(IWebDriver webDriver, WebDriverWait wait,
            AcceptanceTestSettings settings, SightingsDriver sightingsDriver)
        {
            _webDriver = webDriver;
            _wait = wait;
            _sightingsDriver = sightingsDriver;
            _dashboardUrl = $"{settings.BaseUrl.TrimEnd('/')}/Dashboard";
        }

        [AfterScenario("photo-quality")]
        public void CleanupGeneratedImage()
        {
            if (_generatedImagePath is not null && File.Exists(_generatedImagePath))
                File.Delete(_generatedImagePath);
        }

        #region Given

        [Given("Alex is on the Sighting Upload page")]
        public void GivenAlexIsOnTheSightingUploadPage()
        {
            _sightingsDriver.NavigateToSightingsUpload();
        }

        #endregion

        #region When

        [When("Alex submits a sighting with a {string} image")]
        [When("Alex submits a sighting with an {string} image")]
        public void WhenAlexSubmitsASightingWithAnImage(string imageQuality)
        {
            _generatedImagePath = GenerateTestImage(imageQuality);

            // Fill in the other required fields with sensible defaults so the upload form
            // passes server-side validation and reaches the photo-quality analyzer.
            // NOTE: timestamp must use LOCAL time (DateTimeOffset.Now) — the form input is
            // formatted as "yyyy-MM-ddTHH:mm" with no offset, so MVC re-parses it as local
            // time. Using UtcNow here would put the value in the future from the server's
            // perspective and trip the [PastDateTime] validator.
            // Make the description globally unique so the Then-step lookup can match it
            // even when sibling scenarios in the same run have already inserted rows.
            _currentSightingDescription = $"CSP-122 {imageQuality} {Guid.NewGuid():N}";

            _sightingsDriver.SetLatitude(44.847600);
            _sightingsDriver.SetLongitude(-123.234300);
            _sightingsDriver.SetTimestamp(DateTimeOffset.Now.AddDays(-1));
            _sightingsDriver.SetDescription(_currentSightingDescription);

            _sightingsDriver.UploadFileAndSubmit(_generatedImagePath);

            // Successful upload redirects to /Dashboard. Wait for that before asserting anything.
            _wait.Until(d => d.Url.Contains("/Dashboard", StringComparison.InvariantCultureIgnoreCase));
        }

        #endregion

        #region Then

        [Then("Alex should see the warning {string}")]
        public void ThenAlexShouldSeeTheWarning(string warningText)
        {
            var element = _wait.Until(d => d.FindElement(By.Id("photoQualityWarning")));
            element.Text.Should().Contain(warningText);
        }

        [Then("Alex should see the badge {string}")]
        public void ThenAlexShouldSeeTheBadge(string badgeText)
        {
            var element = _wait.Until(d => d.FindElement(By.Id("photoQualityBadge")));
            element.Text.Should().Contain(badgeText);
        }

        [Then("the saved sighting should have QualityTier {string}")]
        public void ThenTheSavedSightingShouldHaveQualityTier(string expectedTier)
        {
            var expected = Enum.Parse<PhotoQualityTier>(expectedTier);
            var sighting = GetMostRecentSightingForAlex();
            sighting.QualityTier.Should().Be(expected);
        }

        [Then("the saved sighting's SharpnessScore should be recorded")]
        public void ThenTheSavedSightingsSharpnessScoreShouldBeRecorded()
        {
            var sighting = GetMostRecentSightingForAlex();
            sighting.SharpnessScore.Should().NotBeNull("CSP-122 service must populate SharpnessScore");
        }

        [Then("the saved sighting's LuminanceAverage should be recorded")]
        public void ThenTheSavedSightingsLuminanceAverageShouldBeRecorded()
        {
            var sighting = GetMostRecentSightingForAlex();
            sighting.LuminanceAverage.Should().NotBeNull("CSP-122 service must populate LuminanceAverage");
        }

        #endregion

        #region Helpers — image generation

        // Produces a PNG on disk whose pixels deterministically map to a CSP-122 tier outcome.
        // Returns the absolute file path so SightingsDriver can hand it to the file input.
        private static string GenerateTestImage(string quality)
        {
            var path = Path.Combine(Path.GetTempPath(), $"csp122_{quality}_{Guid.NewGuid():N}.png");

            using Image<Rgba32> image = quality switch
            {
                // Solid mid-gray, ≥1024 px long side. Sharpness ≈ 0 (< 100) → Low (blurry path).
                "blurry"       => new Image<Rgba32>(1280, 960, new Rgba32(128, 128, 128, 255)),
                // Solid near-black. Luminance ≈ 0.04 (< 0.20) → Low (dark warning).
                "low-light"    => new Image<Rgba32>(1280, 960, new Rgba32(10, 10, 10, 255)),
                // Solid near-white. Luminance ≈ 0.94 (> 0.85) → Low (washed-out warning).
                "overexposed"  => new Image<Rgba32>(1280, 960, new Rgba32(240, 240, 240, 255)),
                // Vertical stripes at ≥2048 long side: high Laplacian variance, luminance ≈ 0.5,
                // long side passes High threshold → High tier. Compresses to a tiny PNG.
                "high-quality" => CreateVerticalStripesImage(2400, 1800),
                _ => throw new ArgumentException(
                    $"Unsupported image quality '{quality}'. Expected blurry|low-light|overexposed|high-quality.",
                    nameof(quality))
            };

            image.SaveAsPng(path);
            return path;
        }

        private static Image<Rgba32> CreateVerticalStripesImage(int width, int height)
        {
            var black = new Rgba32(0, 0, 0, 255);
            var white = new Rgba32(255, 255, 255, 255);
            var image = new Image<Rgba32>(width, height);
            image.ProcessPixelRows(accessor =>
            {
                for (int y = 0; y < accessor.Height; y++)
                {
                    var row = accessor.GetRowSpan(y);
                    for (int x = 0; x < row.Length; x++)
                        row[x] = (x % 2 == 0) ? black : white;
                }
            });
            return image;
        }

        #endregion

        #region Helpers — DB access

        private Sighting GetMostRecentSightingForAlex()
        {
            using var scope = GetServiceScope();
            var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

            var alex = dbContext.Users
                .AsNoTracking()
                .FirstOrDefault(u => u.Email == AlexEmail)
                ?? throw new InvalidOperationException(
                    $"Acceptance seed missing: no AspNetUser with Email '{AlexEmail}'.");

            // Prefer the row whose description matches the per-scenario marker (handles
            // out-of-order scenario timestamps). Fall back to Alex's most-recent row if
            // the description didn't round-trip exactly.
            var recentForAlex = dbContext.Set<Sighting>()
                .AsNoTracking()
                .Where(s => s.UserIdentityId == alex.Id)
                .OrderByDescending(s => s.Timestamp)
                .Take(6)
                .ToList();

            var sighting = recentForAlex
                .FirstOrDefault(s => s.Description == _currentSightingDescription)
                ?? recentForAlex.FirstOrDefault()
                ?? throw new InvalidOperationException(
                    $"No sighting found for {AlexEmail} — expected one to have just been uploaded.");

            return sighting;
        }

        private static IServiceScope GetServiceScope()
        {
            var connectionString = _connectionString.Value
                ?? throw new InvalidOperationException(
                    "Connection string unavailable. CSP-122 BDD tests require " +
                    "MH.Capstone.WebApp/appsettings.Acceptance.json with ConnectionStrings:DataDb set.");

            // Match CSP-101's resilience knobs: Azure SQL serverless can take ~30s to wake.
            var builder = new SqlConnectionStringBuilder(connectionString) { ConnectTimeout = 120 };

            var services = new ServiceCollection();
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(builder.ConnectionString, sql =>
                {
                    sql.CommandTimeout(120);
                    sql.EnableRetryOnFailure(maxRetryCount: 5, maxRetryDelay: TimeSpan.FromSeconds(15), errorNumbersToAdd: null);
                }));
            services.AddIdentityCore<ApplicationUser>().AddEntityFrameworkStores<ApplicationDbContext>();
            services.AddLogging();

            return services.BuildServiceProvider().CreateScope();
        }

        private static string? LoadConnectionString()
        {
            var settingsPath = FindWebAppDevSettings();
            if (settingsPath is null)
                return null;

            using var stream = File.OpenRead(settingsPath);
            using var doc = JsonDocument.Parse(stream);

            if (doc.RootElement.TryGetProperty("ConnectionStrings", out var conn) &&
                conn.TryGetProperty("DataDb", out var dataDb) &&
                dataDb.ValueKind == JsonValueKind.String)
            {
                return dataDb.GetString();
            }
            return null;
        }

        private static string? FindWebAppDevSettings()
        {
            var dir = new DirectoryInfo(AppContext.BaseDirectory);
            while (dir is not null)
            {
                var candidate = Path.Combine(dir.FullName, "MH.Capstone.WebApp", "appsettings.Acceptance.json");
                if (File.Exists(candidate))
                    return candidate;
                dir = dir.Parent;
            }
            return null;
        }

        #endregion
    }
}
