using System.Diagnostics.CodeAnalysis;
using FluentAssertions;
using MH.Capstone.Tests.Acceptance.Drivers;
using NUnit.Framework;
using OpenQA.Selenium;
using Reqnroll;

namespace MH.Capstone.Tests.Acceptance.StepDefinitions;

[Binding]
[ExcludeFromCodeCoverage]
public class CSP125StepDefinitions
{
    private readonly IWebDriver _driver;
    private readonly AuthenticationDriver _authDriver;
    private readonly ClubsDriver _clubsDriver;
    private readonly SightingsDriver _sightingsDriver;

    // Holds the path of a temp file for Sighting image uploads.
    private string? _preparedImageFilePath;

    // Shared across steps within this scenario; lets the Then steps know
    // which club name to look for without re-parsing the URL.
    private string _newClubName = string.Empty;

    public CSP125StepDefinitions(
        IWebDriver driver,
        AuthenticationDriver authDriver,
        ClubsDriver clubsDriver,
        SightingsDriver sightingsDriver)
    {
        _driver = driver;
        _authDriver = authDriver;
        _clubsDriver = clubsDriver;
        _sightingsDriver = sightingsDriver;
    }

    // Scenario 1: Alex is on his front Club page

    [Given("I am on the Club front page")]
    public void GivenIAmOnTheClubFrontPage()
    {
        _authDriver.PreformLoginForUser("alex@test.com", "Capstone26!");
        _clubsDriver.NavigateToLandingPage();

        // Create a fresh club for this scenario and invite Lily so her seeded sightings appear in the feed.
        var uid = Guid.NewGuid().ToString("N")[..8];
        _newClubName = $"Feed_{uid}";
        _clubsDriver.OpenCreateClubModal();
        _clubsDriver.FillCreateClubModal(_newClubName, null, isPublic: true);
        _clubsDriver.SubmitCreateClubModal();
        _clubsDriver.InviteMemberByDisplayName("Lily");

        // Switch to Lily, accept the invite, then return to Alex on the landing page.
        _authDriver.LogoutUser();
        _authDriver.PreformLoginForUser("lily@test.com", "Capstone26!");
        _clubsDriver.NavigateToLandingPage();
        _clubsDriver.AcceptInviteForClub(_newClubName);

        _authDriver.LogoutUser();
        _authDriver.PreformLoginForUser("alex@test.com", "Capstone26!");
        _clubsDriver.NavigateToLandingPage();
    }

    [When("I look under the Club name and description")]
    public void WhenILookUnderTheClubNameAndDescription()
    {
        _clubsDriver.NavigateToClubPage(_newClubName);
    }

    [Then("I should see the newest Sightings from the other Club members")]
    public void ThenIShouldSeeTheNewestSightingsFromTheOtherClubMembers()
    {
        _clubsDriver.HasAnySightingCards().Should().BeTrue(
            "the Club feed should show sightings from other members");
    }

    [Then("the front page should update if I upload a new Sighting")]
    public void ThenTheFrontPageShouldUpdateIfIUploadANewSighting()
    {
        // Go to sighting upload page
        _sightingsDriver.NavigateToSightingsUpload();

        // Create a Sighting, upload it
        // Create a minimal JPEG file (magic bytes + a few padding bytes).
        // ValidateImage checks content-type (derived from the .jpg extension by the
        // browser) and that size is between 1 byte and 2 MB — actual pixel data is
        // not inspected, so magic bytes alone are sufficient.
        var path = Path.Combine(Path.GetTempPath(), $"valid_image_{Guid.NewGuid()}.jpg");
        byte[] minimalJpeg =
        [
            0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46, // JFIF SOI + APP0 marker
            0x49, 0x46, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01,
            0x00, 0x01, 0x00, 0x00, 0xFF, 0xD9              // EOI
        ];
        File.WriteAllBytes(path, minimalJpeg);
        _preparedImageFilePath = path;

        _sightingsDriver.SetImageForUpload(path);

        // Set the other form fields to valid values as well.
        _sightingsDriver.SetDescription("This was generated by acceptance/system tests.");
        _sightingsDriver.SetLatitude(45.0);
        _sightingsDriver.SetLongitude(88.79);
        _sightingsDriver.SetTimestamp(DateTimeOffset.Now);

        // Submit the Sighting
        _sightingsDriver.SubmitSightingsForm();

        // Navigate back to the club page and verify Alex's new Sighting appears in the feed.
        _clubsDriver.NavigateToLandingPage();
        _clubsDriver.NavigateToClubPage(_newClubName);
        _clubsDriver.IsSightingByUserVisible("Alex").Should().BeTrue(
            "Alex's newly uploaded Sighting should appear in the Club feed");
    }

    // Scenario 2: Lily leaves the Club, and Alex is on the front Club page

    [Given("Lily leaves the Club")]
    public void GivenLilyLeavesTheClub()
    {
        // Switch to Lily, navigate to the club, and leave it.
        _authDriver.LogoutUser();
        _authDriver.PreformLoginForUser("lily@test.com", "Capstone26!");
        _clubsDriver.NavigateToLandingPage();
        _clubsDriver.NavigateToClubPage(_newClubName);
        _clubsDriver.LeaveClub();

        // Return to Alex on the landing page so the When step can navigate to the club.
        _authDriver.LogoutUser();
        _authDriver.PreformLoginForUser("alex@test.com", "Capstone26!");
        _clubsDriver.NavigateToLandingPage();
    }

    [Then("I should see it update to remove Lily Sightings from the feed")]
    public void ThenIShouldSeeItUpdateToRemoveLilySightingsFromTheFeed()
    {
        _clubsDriver.IsSightingByUserVisible("Lily").Should().BeFalse(
            "Lily's sightings should no longer appear in the feed after she left the Club");
    }
}
