# WARNING: This workflow/action can only be run on the main repo (jmcshane22/MonmouthHoldemCapstone)
name: Deploy to Azure

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write  # Required for Azure OIDC login in deploy job

jobs:
  build:
    if: github.repository == 'jmcshane22/MonmouthHoldemCapstone'
    uses: ./.github/workflows/build.yml 
        

  complete_test_suite_run:
    needs: build
    if: github.repository == 'jmcshane22/MonmouthHoldemCapstone'
    uses: ./.github/workflows/test_suite_complete_run.yml
    secrets: inherit  # so the system_tests workflow can access secrets

  publish:
    if: github.repository == 'jmcshane22/MonmouthHoldemCapstone'
    runs-on: ubuntu-latest
    needs: [build,complete_test_suite_run]
    permissions:
      actions: read  # Required to download artifact from the source run
    outputs:
      version: ${{ steps.get_build_version.outputs.version }}
      artifact_name: ${{ vars.FILEPATH_SAFE_APPNAME }}_v${{ steps.get_build_version.outputs.version }}
    steps:
      - name: Download artifact from build job
        id: artifact_download
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.sha }}
          run-id: ${{ needs.build.outputs.source_run_id }}
          github-token: ${{ github.token }}
          path: ./src

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Get build version number
        id: get_build_version
        run: echo "version=$(cat ${{ vars.VERSION_FILE }})" >> $GITHUB_OUTPUT

      - name: Publish
        id: publish_app
        run: |
          dotnet publish ./src/MH.Capstone.WebApp --no-restore --no-build --configuration Release --verbosity ${{ vars.DOTNET_VERBOSE_LVL }} \
          -o "${{ vars.PUBLISH_ROOT_DIR }}/${{ vars.WEBAPP_PUBLISH_DIR }}"

  config:
    if: github.repository == 'jmcshane22/MonmouthHoldemCapstone'
    runs-on: ubuntu-latest
    env:
      prod_env: azure_prod
      staging_env: azure_staging
    outputs:
      deploy_env: ${{ steps.output_configs.outputs.deploy_env }}
      is_prerelease: ${{ steps.output_configs.outputs.is_prerelease }}
    steps:
      - name: Set config values for PROD (branch main)
        if: github.ref_name == 'main'
        id: config_prod
        run: |
          echo "::notice::Deployment being configured under PROD. Branch name is ${{ github.ref_name }}";
          echo "ISPRE=false" >> "$GITHUB_ENV";
          echo "DENV=${{ env.prod_env }}" >> "$GITHUB_ENV";
      
      - name: Set config values for STAGING (branch dev)
        if: github.ref_name == 'dev'
        id: config_staging
        run: |
          echo "::notice::Deployment being configured under STAGING. Branch name is ${{ github.ref_name }}";
          echo "ISPRE=true" >> "$GITHUB_ENV";
          echo "DENV=${{ env.staging_env }}" >> "$GITHUB_ENV";

      - name: Output config values
        if: always()
        id: output_configs
        run: |
          echo "is_prerelease=${{ env.ISPRE }}" >> "$GITHUB_OUTPUT";
          echo "deploy_env=${{ env.DENV }}" >> "$GITHUB_OUTPUT";

  release:
    if: github.repository == 'jmcshane22/MonmouthHoldemCapstone'
    runs-on: ubuntu-latest
    needs: [publish,config]
    env:
      ARTIFACT_ZIP_NAME: ${{ needs.publish.outputs.artifact_name }}.zip
    permissions:
      contents: write #This is required for the release action
      
    steps:
      - name: Download artifact from publish job
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.publish.outputs.artifact_name }}
          path: app

      - name: Zip artifact for release
        run: zip -r ${{ env.ARTIFACT_ZIP_NAME }} ./app

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: ${{ needs.config.outputs.is_prerelease }}
          name: ${{ needs.publish.outputs.version }}
          tag_name: ${{ needs.publish.outputs.version }}
          generate_release_notes: true
          files: ${{ env.ARTIFACT_ZIP_NAME }}
          target_commitish: ${{ github.sha }}

  deploy:
    if: github.repository == 'jmcshane22/MonmouthHoldemCapstone'
    runs-on: ubuntu-latest
    needs: [publish,config]
    environment:
      name: ${{ needs.config.outputs.deploy_env }}
    env:
      ASPNETCORE_ENVIRONMENT: Production
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from publish job
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.publish.outputs.artifact_name }}
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZUREAPPSERVICE_APPNAME }}
          slot-name: 'Production'
          package: .

      - name: Deploy EF Core migration bundle - ApplicationDbContext
        id: deploy-application-db-ctx
        if: ${{ success() }}
        run: |
          chmod +x ${{ vars.DOTNET_EF_BUNDLE_NAME_APPDBCTX }} &&
          ${{ vars.DOTNET_EF_BUNDLE_NAME_APPDBCTX }} --connection '${{ secrets.AZUREAPPSERVICE_DBCONNSTR }}' --verbose

      - name: Deploy EF Core migration bundle - CacheDbContext
        id: deploy-cache-db-ctx
        if: ${{ success() }}
        run: |
          chmod +x ${{ vars.DOTNET_EF_BUNDLE_NAME_CACHEDBCTX }} &&
          ${{ vars.DOTNET_EF_BUNDLE_NAME_CACHEDBCTX }} --connection '${{ secrets.AZUREAPPSERVICE_DBCONNSTR }}' --verbose