# WARNING: This workflow/action can only be run on the main repo (jmcshane22/MonmouthHoldemCapstone)
name: Run Integration & E2E Tests (System Tests)

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  actions: read
  id-token: write  # Required for Azure OIDC login

jobs:
  build:
    if: github.repository == 'jmcshane22/MonmouthHoldemCapstone'
    uses: ./.github/workflows/build.yml

  system_tests:
    needs: build
    if: github.repository == 'jmcshane22/MonmouthHoldemCapstone'
    runs-on: ubuntu-latest
    permissions:
      actions: read    # Required to download artifact from the source run
      id-token: write  # Required for Azure OIDC login
      contents: read
    environment: system_testing
    env:
      # For color output from the dotnet commands. ENVs are scoped to all steps in the job
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm-256color
      ASPNETCORE_ENVIRONMENT: Acceptance

    steps:
      - name: Download artifact from build job
        id: artifact_download
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.sha }}
          run-id: ${{ needs.build.outputs.source_run_id }}
          github-token: ${{ github.token }}
          path: ./src

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SYSTEST_AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.SYSTEST_AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.SYSTEST_AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Give execution permissions to entire project build directory
        run: chmod -R +x ./src

      - name: Ensure test database is migrated and ok
        run: |
          ./src/${{ vars.DOTNET_EF_BUNDLE_DIR }}/${{ vars.DOTNET_EF_BUNDLE_NAME_APPDBCTX }} \
            --connection '${{ secrets.SYSTEST_AZUREAPPSERVICE_DBCONNSTR }}' --verbose &&
          ./src/${{ vars.DOTNET_EF_BUNDLE_DIR }}/${{ vars.DOTNET_EF_BUNDLE_NAME_CACHEDBCTX  }} \
            --connection '${{ secrets.SYSTEST_AZUREAPPSERVICE_DBCONNSTR }}' --verbose
      
      - name: Run Integration & Acceptance (BDD/Gherkin/Reqnroll) Tests
        env:
          ConnectionStrings__DataDb: ${{ secrets.SYSTEST_AZUREAPPSERVICE_DBCONNSTR }}
          ConnectionStrings__AzureCommunicationServices: ${{ secrets.SYSTEST_AZURECOMMSERVICE_CONNSTR }}
          Api__External__Ninjas__ApiKey: ${{ secrets.SYSTEST_NINJASAPI_APIKEY }}
        run: |
          ls -a ./src ;
          dotnet test ./src/MH.Capstone.Tests.Integration --no-restore --no-build --configuration Release --verbosity ${{ vars.DOTNET_VERBOSE_LVL }} ;
          dotnet test ./src/MH.Capstone.Tests.Acceptance --no-restore --no-build --configuration Release --verbosity ${{ vars.DOTNET_VERBOSE_LVL }}
